---
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - prettier
plugins:
  - '@typescript-eslint'
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  sourceType: module
  project: './tsconfig.json'
rules:
  prettier/prettier: error
  block-scoped-var: error
  eqeqeq: error
  no-warning-comments: warn
  no-var: error
  prefer-const: error
  '@typescript-eslint/no-unused-vars': off