apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: supershop-backend
build:
  googleCloudBuild: {}
  artifacts:
    - image: gcr.io/shomaj-817b0/supershop-backend
      context: .
      docker:
        dockerfile: Dockerfile
deploy:
  cloudrun:
    region: asia-southeast1
portForward: []